config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    root "dashboards#index"

    get "dashboard" => "dashboards#index"

    devise_scope :user do
      get '/sign_in' => 'devise/sessions#new'
      get '/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]

      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :orders, only: [:show,:index]
      resources :customers
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations
    end

    root "homes#index"
    resources :homes
    resources :products
    get "customer_info/:id" => "customers#customer_info", :as => :customer_info
    get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
    patch "customer_info/:id" => "customers#update_customer_info"
    put "customer_info/:id" => "customers#update_customer_info"
    get "product_detail/:id" => "products#product_detail", :as => :product_detail
    resources :customers
    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    get "cart/remove/:id" => "cart#remove"
    post "cart/checkout" => "cart#checkout", :as => :checkout

    get "products" => "products#add", :as => :product_cart

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
end

app/models/order.rb
class Order < ApplicationRecord
  #Association
  has_many :line_items, :dependent => :destroy
  belongs_to :customer
  #Scope
  scope :in_progress, ->{where("orders.checked_out_at IS NULL")}
  scope :complete, -> {where("orders.checked_out_at IS NOT NULL")}

  COMPLETE = "complete"
  IN_COMPLETE = "in_complete"

  #Class Method
  def self.find_with_product(product)
    return [] unless product
    complete.joins(:line_items).where(["line_items.product_id = ?", product.id]).order("orders.checked_out_at DESC")
  end

  #Instance Method
  def checkout!
    self.checked_out_at = Time.now
    self.save
  end

  def recalculate_price!
    self.total_price = line_items.inject(0.0){|sum, line_item| sum += line_item.sub_total }
    save!
  end

  def state
    checked_out_at.nil? ? IN_COMPLETE : COMPLETE
  end

  # def self.count_complete_item
  #   where("checked_out_at <> ?", !nil).count
  # end
  # def display_name
  #   ActionController::Base.helpers.number_to_currency(total_price) +
  #       " - Order ##{id} (#{user.username})"
  # end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!
  before_action :admin_only, except: [:index,:show]
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :notice => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :checked_out_at, :total_price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id, id: :order_customer_id %>
  </div>

  <div class="field">
    <%= form.label :checked_out_at %>
    <%= form.datetime_select :checked_out_at, id: :order_checked_out_at %>
  </div>

  <div class="field">
    <%= form.label :total_price %>
    <%= form.text_field :total_price, id: :order_total_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Checked out at</th>
      <th>State</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer.email %></td>
        <%if order.state == "in_complete"%>
          <td>Null</td>
        <%else%>
          <td><%= order.checked_out_at %></td>
        <%end%>
        <td><%= order.state%></td>
        <%if order.state == "in_complete"%>
          <td><%=number_to_currency(0)%></td>
        <%else%>
          <td><%= number_to_currency(order.total_price) %></td>
        <%end%>

        <%if current_admin_user.admin?%>
          <td><%= link_to 'Show', admin_order_path(order) %></td>
          <td><%= link_to 'Destroy', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', admin_order_path(order) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer.email %>
</p>

<p>
  <strong>Checked out at:</strong>
  <%= @order.checked_out_at %>
</p>

<p>
  <strong>Total price:</strong>
  <%= number_to_currency(@order.total_price) %>
</p>

<%= link_to 'Back', admin_orders_path %>