config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    root "dashboards#index"

    get "dashboard" => "dashboards#index"

    devise_scope :user do
      get '/sign_in' => 'devise/sessions#new'
      get '/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]

      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :orders, only: [:show,:index]
      resources :customers
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations
    end

    root "homes#index"
    resources :homes
    resources :products
    get "customer_info/:id" => "customers#customer_info", :as => :customer_info
    get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
    patch "customer_info/:id" => "customers#update_customer_info"
    put "customer_info/:id" => "customers#update_customer_info"
    get "product_detail/:id" => "products#product_detail", :as => :product_detail
    resources :customers
    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    get "cart/remove/:id" => "cart#remove"
    post "cart/checkout" => "cart#checkout", :as => :checkout

    get "products" => "products#add", :as => :product_cart

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :user
  belongs_to :stock_location
  belongs_to :product
end

app/controllers/admin/stock_items_controller.rb
class Admin::StockItemsController < AdminApplicationController
  before_action :set_stock_item, only: [:index,:stock,:new,:create,:edit,:update,:destroy]
  before_action :authenticate_admin_user! , only: [:index,:new,:edit,:update,:destroy,:set_stock_item,:stock]
  before_action :admin_only, except: [:index,:show]

  # GET /stock_items
  # GET /stock_items.json

  def stock
    @stock_item = current_admin_user.stock_items.build
  end

  def index
    @stock_items = @product.stock_items.joins(:product)
    @fields = ["Product","Quantity", "Stock Location"]
  end

  # GET /stock_items/1
  # GET /stock_items/1.json
  def show

  end

  # GET /stock_items/new
  def new
  end

  # GET /stock_items/1/edit
  def edit
  end

  # POST /stock_items
  # POST /stock_items.json
  def create
    @product.save
    @stock = @product.stock_items.build(stock_item_params)
    @stock.user = current_admin_user
    respond_to do |format|
      if @stock.save
        format.html{ redirect_to admin_product_stock_path, notice: "Stock Has Been Added" }
      else
        format.html{ render :stock }
      end
    end
    # respond_to do |format|
    #   if @stock_item.save
    #
    #       redirect_to admin_product_stock_path,
    #       flash[:success] = 'Stock item was successfully created.'
    #     format.json { render :show, status: :created, location: @stock_item }
    #   else
    #     format.html { render :stock }
    #     format.json { render json: @stock_item.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /stock_items/1
  # PATCH/PUT /stock_items/1.json
  def update
    respond_to do |format|
      if @stock_item.update(stock_item_params)
        format.html { redirect_to admin_product_stock_items, notice: 'Stock item was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock_item }
      else
        format.html { render :edit }
        format.json { render json: @stock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stock_items/1
  # DELETE /stock_items/1.json
  def destroy
    @stock_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_stock_items_url, notice: 'Stock item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock_item
      @product = current_admin_user.products.find(params[:product_id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :notice => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_item_params
      params.require(:stock_item).permit(:product_id, :stock_location_id, :count_on_hand,:quantity)
    end
end

app/helpers/stock_items_helper.rb
module StockItemsHelper
end

app/views/admin/stock_items/_form.html.erb
<%= form_with(model: stock_item, local: true) do |form| %>
  <% if stock_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock_item.errors.count, "error") %> prohibited this stock_item from being saved:</h2>

      <ul>
      <% stock_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :stock_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :stock_location_id %>
    <%= form.number_field :stock_location_id, id: :stock_item_stock_location_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :stock_item_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/stock_items/edit.html.erb
<h1>Editing Stock Item</h1>

<%= render 'form', stock_item: @stock_item %>

<%= link_to 'Show', @stock_item %> |
<%= link_to 'Back', stock_items_path %>

app/views/admin/stock_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stock Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Stock location</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stock_items.each do |stock_item| %>
      <tr>
        <td><%= stock_item.product.product_name %></td>
        <td><%= stock_item.stock_location.stock_name %></td>
        <td><%= stock_item.quantity %></td>
        <td><%= stock_item.product.user.email%></td>
        <%if current_admin_user.admin?%>
          <td><%= link_to 'Show', admin_stock_location_path(stock_item.stock_location.id) %></td>
          <td><%= link_to 'Edit', edit_admin_stock_location_path(stock_item) %></td>
          <td><%= link_to 'Destroy', admin_stock_location_path(stock_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', admin_stock_location_path(stock_item.stock_location.id) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock Item', new_admin_stock_location_path %>

app/views/admin/stock_items/new.html.erb
<h1>New Stock Item</h1>

<%= render 'form', stock_item: @stock_item %>

<%= link_to 'Back', stock_items_path %>

app/views/admin/stock_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @stock_item.product_id %>
</p>

<p>
  <strong>Stock location:</strong>
  <%= @stock_item.stock_location_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @stock_item.quantity %>
</p>
<%if current_admin_user.admin?%>
  <%= link_to 'Edit', edit_stock_item_path(@stock_item) %> |
  <%= link_to 'Back', stock_items_path %>
<%else%>
  <%= link_to 'Back', stock_items_path %>
<%end%>

app/views/admin/stock_items/stock.html.erb
<%= notice %>
<%=@product.count_on_hand%>
<%=form_for([:admin, @product, @stock_item])do |f|%>
  <div class="field">
    <%=f.label :quantity%>
    <%=f.number_field :quantity, :placeholder=>"Qty"%><br>
  </div>

  <div class="field">
    <%=f.label "Stock Location"%>
    <%=f.collection_select :stock_location_id, StockLocation.all, :id, :stock_name%><br>
  </div>


  <div class="actions">
    <%=f.submit%>
  </div>

<%end%>