config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    root "dashboards#index"

    get "dashboard" => "dashboards#index"

    devise_scope :user do
      get '/sign_in' => 'devise/sessions#new'
      get '/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]

      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :orders, only: [:show,:index]
      resources :customers
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations
    end

    root "homes#index"
    resources :homes
    resources :products
    get "customer_info/:id" => "customers#customer_info", :as => :customer_info
    get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
    patch "customer_info/:id" => "customers#update_customer_info"
    put "customer_info/:id" => "customers#update_customer_info"
    get "product_detail/:id" => "products#product_detail", :as => :product_detail
    resources :customers
    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    get "cart/remove/:id" => "cart#remove"
    post "cart/checkout" => "cart#checkout", :as => :checkout

    get "products" => "products#add", :as => :product_cart

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!
  before_action :admin_only, except: [:index,:show]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = current_admin_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_admin_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :notice => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, id: :category_category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= category.user.email%></td>
        <%if current_admin_user.admin?%>
          <td><%= link_to 'Show', admin_category_path(category) %></td>
          <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
          <td><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', admin_category_path(category) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>
<%if current_admin_user.admin?%>

<%else%>

<%end%>
<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>