config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    root "dashboards#index"

    get "dashboard" => "dashboards#index"

    devise_scope :user do
      get '/sign_in' => 'devise/sessions#new'
      get '/sign_up' => 'devise/registrations#new', :as => 'new_user_registration'
    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :skip => [:registrations]

      as :user do
        get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
        put 'users' => 'devise/registrations#update', :as => 'user_registration'
        patch 'users' => 'devise/registrations#update'
      end

      resources :users
      resources :categories
      resources :orders, only: [:show,:index]
      resources :customers
      resources :products do
        resources :stock_items
        get "stock" => "stock_items#stock", :as => "stock"
      end
      resources :stock_locations
    end

    root "homes#index"
    resources :homes
    resources :products
    get "customer_info/:id" => "customers#customer_info", :as => :customer_info
    get "customer_info/:id/edit_customer_info" => "customers#edit_customer_info", :as => "edit_customer_info"
    patch "customer_info/:id" => "customers#update_customer_info"
    put "customer_info/:id" => "customers#update_customer_info"
    get "product_detail/:id" => "products#product_detail", :as => :product_detail
    resources :customers
    get "cart" => "cart#show"
    get "cart/add/:id" => "cart#add", :as => :add_to_cart
    post "cart/remove/:id" => "cart#remove", :as => :remove_from_cart
    get "cart/remove/:id" => "cart#remove"
    post "cart/checkout" => "cart#checkout", :as => :checkout

    get "products" => "products#add", :as => :product_cart

    post 'session' => 'sessions#create', :as=> :session_customer
    get 'signup' => 'customers#new',:as=> :signup
    get 'logout' => 'sessions#destroy', :as => :logout
    get 'login' => 'sessions#new', :as => :login
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :stock_items
  has_many :stock_location, :through => :stock_items
  has_many :line_items

  def count_on_hand
    # count = stock_items.sum(:quantity)
    # if count == 0
    #   "Out Of Stock"
    # else
    #   return count
    # end
  end

  def cut_stock
    # count = count_on_hand
    # if count == 0 || count <= 0
    #   "Out Of Stock"
    # else
    #   return count
    # end
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!
  before_action :admin_only, except: [:index,:show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_admin_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_admin_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def admin_only
      unless current_admin_user.admin?
        redirect_to admin_dashboard_path, :notice => "Access denied."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :sku, :category_id, :user_id,:price,:quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_cart
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  private
    def find_cart
      if current_customer
        @cart = session[:cart_id] ? Order.find(session[:cart_id]) : current_customer.orders.build
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def count_cart
    @cart.line_items.count
  end
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :product_product_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, :placeholder => "Qty" %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku, id: :product_sku %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, :placeholder => "Price" %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>
<%= link_to "Stock", admin_product_stock_path(@product)%>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Price</th>
      <th>Sku</th>
      <th>Category</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= number_to_currency(product.price)%></td>
        <td><%= product.sku %></td>
        <td><%= product.category_id %></td>
        <td><%= product.count_on_hand%></td>
        <%if current_admin_user.admin?%>
          <td><%= link_to 'Show', admin_product_path(product) %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
          <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
          <td><%= link_to 'Show', admin_product_path(product) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @product.sku %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Price</strong>
  <%= number_to_currency(@product.price)%>
</p>
<%if current_admin_user.admin?%>
  <%= link_to 'Edit', edit_admin_product_path(@product) %> |
  <%= link_to 'Back', admin_products_path %>
<%else%>
  <%= link_to 'Back', admin_products_path %>
<%end%>